language: node_js
node_js:
- '8'
dist: trusty
sudo: false
install:
- npm install
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: F3pz3DlJlNZs4l/8E6nG4SUM9Thoz0T6CPbb9zJQMA0sJg9u/3HpptfC3rcBtrTmH83tSqgQBqqgFqzazeD4aPwFHWB9xJglCDP0i7rmFmZ7muHpe0i6FTojSPGCyVgZnOy4ykqNi5l57+zE3Hbyxi35B1NPSnAi9hPJmie2jHMDd7dNFmRgQB80/HrXHjFC0F10uuxRlzHWgnhh9WdU4YhC1mWlXhf5EQ0ujPo0vQPNz1/W6AWoJFMr0y0I6f9O1Ydd5xXCjRSYdsyHKz1gYNgBOUYe1IfPyAtvNnsZUP7EJq5SvtALCf75psovwiFceHKZ9r4eOwOtJSxoRO6hFt3s1Dg6Gtaba8P3SoLRcFSbrXWfuSTSXVmQb5KRHtC6zGaQz2kza1cmqoHzEm58tkfKyG9Kg5v1zmLfEg28zRsv6OLYz/YEq+X/JjT2/JZ8dWuk84cU1bquHrN17drbQzezhduWjs0gm4cSjBZpCJQQndkVcFur53MWTkxBtDtbEmyb1qJhW2L/kgsmrdZ54MKDr0nx2zQH1reZ9iCn8rflIsL6NDaMyk6x7Fx9yUM8EKTF2KnzYV173l5GR6a3kWTc3KDgj3ANfgyqNXBJfDV4TjGzkqei5zYl9gUmQjN46xU89QscackWovGOpdtMzmEzKkJjEHJfx2Kjzxq2WQg=
  on:
    branch: master
    repo: Cimpress-MCP/grunt-aws-swaggerimport
