language: node_js
node_js:
- '8'
dist: trusty
sudo: false
install:
- npm install
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: MpUPHly1s8pYZML9JxOc9iRFnD85WngRQOx5YCxd8qVJg8Yqios5ZuYZE53+JxSlM816v7sZyjARo+vE742l6JTq93v1CI8/rLast/Rr5mSOzexrBn7nohEc1z8ex5UTavGsi77UjWcvD5dUFUsQMcFV9JkaHHlBPkRn/Esbti/D23rcSJJOU44cnaXNWZF6+UfjIXT8EOQi3KtpWXUTgBjKByEXqLSfehuZckBMW11N7TNTsXTheaWQG9dprcdcFq9k7w40Mz5PCrRvyieoFtK/N8agvqPTzY9mBfe3e635Y9a3SDKjT0GBJOwm4DRrtiGajzeSpSWRT4454iWiQGlwYbHFG0paFvTgGws8rdqJc4KaDgkCTXw/GB/6/7mMFgStN/2bNBm3NnzIAjMtW+HA2bOtM/Um3HCeTeVsLCcAvhv+HWGy0FJp7UmmIxPjKVkTDEK7GaasD/R0F6MWuypQ/Zf3x/pQhIRXd+DgR4iGZT2JnjrE2ExH6Ah2oD0PCePjdgfuzi0SPtyvO7BR0GJAtZkzvhL7O53Hth3ifTiuymgHerzqHf9xautXnvxs2JUa4rPSkesgU5CXFlGTSfk1u7RlAMCFPIPRoykqE3K8eOCwQY7dRNiDjm5oYlkLiKUOQCUBcqLs7HU53zIkPX6P6OKhxkhsL11WzsJadTw=
  on:
    branch: master
    repo: Cimpress-MCP/grunt-aws-swaggerimport
